name: sonar-scanner

on:
  pull_request:
    branches:
    - master 
  push: 
    branches: 
    - master

jobs:
  SonarScanner:
    if: github.repository == 'freewms/PDE'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Configure env vars for SonarCloud scan
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        echo "::set-env name=PATH::/opt/sonar-scanner/bin:$PATH"
    
    - name: Compute branch name
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      uses: nixel2007/branch-name@v3
    
    - name: Извлечение версии
      shell: bash
      run: echo "##[set-output name=version;]` cat ./src/Configuration/Configuration.mdo | grep -oP '(?<=<version>).*(?=</version>)'`"
      id: extract_version

    - name: SonarCloud Scan on push
      if:  github.event_name == 'push'
      uses: nixel2007/sonarcloud-github-action@v1.4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.host.url=https://sonar.openbsl.ru
          -Dsonar.branch.name=${{ env.BRANCH_NAME }}
          -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}
           
    - name: SonarCloud Scan on PR
      if: github.event_name == 'pull_request'
      uses: nixel2007/sonarcloud-github-action@v1.4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.host.url=https://sonar.openbsl.ru
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
